[project]
name = "yesterdays"
version = "0.1.0"
description = "A Django web application for georeferencing historical images."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4~=4.15.0",
    "boto3~=1.43.52",
    "celery[librabbitmq]~=5.6.3",
    "django~=6.0.7",
    "django-celery-results>=2.6.0",
    "django-cors-headers~=4.9.0",
    "django-filter~=25.2",
    "django-oauth-toolkit>=3.4.0",
    "django-prometheus~=2.5.0",
    "django-ratelimit~=4.1.0",
    "django-vite~=3.1.0",
    "djangorestframework~=3.17.1",
    "djangorestframework-gis~=1.2.1",
    "drf-spectacular~=0.30.0",
    "edtf~=5.0.1",
    "flickrapi~=2.4.0",
    "geopy~=2.4.1",
    "iiif-prezi3==3.1.1",
    "markdown~=3.10.2",
    "nh3~=0.3.6",
    "numpy>=2.5.1",
    "osm-login-python~=2.1.4",
    "pillow==12.0.0",
    "psycopg[binary]~=3.3.4",
    "pyoxigraph>=0.5.9",
    "pytesseract>=0.3.13",
    "pyvips>=3.1.1",
    "requests~=2.34.2",
    "tqdm~=4.69.0",
    "uvicorn[standard]~=0.51.0",
    "whitenoise[brotli]~=6.12.0",
]

[dependency-groups]
dev = [
    "pytest-django>=4.11.1",
    "pytest>=9.1.1",
]
docs = ["zensical~=0.0.51"]

[tool.uv]
default-groups = ["docs"]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'"
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "yesterdays.settings"
python_files = "tests.py test_*.py *_tests.py"
