# Generated by Django 5.2.6 on 2025-09-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="image",
            name="images_imag_year_421258_idx",
        ),
        migrations.RemoveField(
            model_name="image",
            name="day",
        ),
        migrations.RemoveField(
            model_name="image",
            name="month",
        ),
        migrations.RemoveField(
            model_name="image",
            name="year",
        ),
        migrations.AddField(
            model_name="image",
            name="creator",
            field=models.CharField(
                help_text="Creator(s) of the work", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="edtf_date",
            field=models.CharField(
                help_text="Date parsed as EDTF", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="original_date",
            field=models.CharField(
                help_text="Date information from source", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="ref",
            field=models.CharField(
                help_text="Source-specific reference", max_length=50, null=True
            ),
        ),
    ]
