# Generated by Django 5.2.6 on 2025-09-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="collection",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="source",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("source", "name", "slug")},
        ),
    ]
