# Generated by Django 5.2.6 on 2025-09-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_add_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="public",
            field=models.BooleanField(
                default=True, help_text="Whether this collection is visible to users"
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="public",
            field=models.BooleanField(
                default=True, help_text="Whether this source is visible to users"
            ),
        ),
    ]
