# Generated by Django 5.2.6 on 2025-09-07 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0003_add_public_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="georeference",
            name="georeferenced_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted the georeference (null for anonymous submissions)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="georeferenced_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
