# Generated by Django 5.2.6 on 2025-09-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_allow_anonymous_georeferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_url',
            field=models.URLField(blank=True, help_text='Original URL from the source website', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='permalink',
            field=models.URLField(help_text='Direct link to the image (CDN or processed URL)'),
        ),
    ]
