# Generated by Django 5.2.6 on 2025-09-10 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_original_url_alter_image_permalink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='georeference',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='georeferences', to='images.image'),
        ),
        migrations.AddIndex(
            model_name='georeference',
            index=models.Index(fields=['image', 'georeferenced_by'], name='images_geor_image_i_ccacbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='georeference',
            constraint=models.UniqueConstraint(condition=models.Q(('georeferenced_by__isnull', False)), fields=('image', 'georeferenced_by'), name='unique_georeference_per_user'),
        ),
    ]
