# Generated by Django 5.2.6 on 2025-09-22 03:02

from django.db import connection, migrations, models


def setup_search_vectors(apps, schema_editor):
    """Setup search vectors and triggers for PostgreSQL only"""
    if connection.vendor != "postgresql":
        # Skip for non-PostgreSQL databases
        return

    schema_editor.execute(
        "ALTER TABLE images_image ALTER COLUMN search_vector TYPE tsvector USING to_tsvector('english', COALESCE(search_vector, ''));"
    )

    # Create function to update search vector
    schema_editor.execute("""
        CREATE OR REPLACE FUNCTION update_image_search_vector() RETURNS trigger AS $func$
        BEGIN
            NEW.search_vector := to_tsvector('english',
                COALESCE(NEW.title, '') || ' ' ||
                COALESCE(NEW.description, '') || ' ' ||
                COALESCE((SELECT c.name FROM images_collection c WHERE c.id = NEW.collection_id), '') || ' ' ||
                COALESCE((SELECT s.name FROM images_source s JOIN images_collection c ON s.id = c.source_id WHERE c.id = NEW.collection_id), '') || ' ' ||
                COALESCE(NEW.original_date, '') || ' ' ||
                COALESCE(NEW.creator, '')
            );
            RETURN NEW;
        END;
        $func$ LANGUAGE plpgsql;
    """)

    # Create trigger
    schema_editor.execute("""
        CREATE TRIGGER image_search_vector_update
            BEFORE INSERT OR UPDATE ON images_image
            FOR EACH ROW EXECUTE FUNCTION update_image_search_vector();
    """)

    # Populate existing records
    schema_editor.execute("""
        UPDATE images_image SET search_vector = to_tsvector('english',
            COALESCE(title, '') || ' ' ||
            COALESCE(description, '') || ' ' ||
            COALESCE((SELECT c.name FROM images_collection c WHERE c.id = images_image.collection_id), '') || ' ' ||
            COALESCE((SELECT s.name FROM images_source s JOIN images_collection c ON s.id = c.source_id WHERE c.id = images_image.collection_id), '') || ' ' ||
            COALESCE(original_date, '') || ' ' ||
            COALESCE(creator, '')
        );
    """)

    # Create GIN index for better search performance
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS images_image_search_vector_idx ON images_image USING GIN(search_vector);"
    )


def teardown_search_vectors(apps, schema_editor):
    """Remove search vectors and triggers for PostgreSQL only"""
    if connection.vendor != "postgresql":
        # Skip for non-PostgreSQL databases
        return

    schema_editor.execute(
        "DROP TRIGGER IF EXISTS image_search_vector_update ON images_image;"
    )
    schema_editor.execute("DROP FUNCTION IF EXISTS update_image_search_vector();")
    schema_editor.execute("DROP INDEX IF EXISTS images_image_search_vector_idx;")
    schema_editor.execute(
        "ALTER TABLE images_image ALTER COLUMN search_vector TYPE text;"
    )
    schema_editor.execute("UPDATE images_image SET search_vector = NULL;")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("images", "0005_image_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="search_vector",
            field=models.TextField(
                blank=True,
                help_text="Full-text search vector for title, description, location, and year",
                null=True,
            ),
        ),
        migrations.RunPython(setup_search_vectors, teardown_search_vectors),
    ]
