# Generated by Django 5.2.6 on 2025-09-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_georeference_image_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='georeference',
            name='unique_georeference_per_user',
        ),
        migrations.AddField(
            model_name='georeference',
            name='confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Confidence level in the accuracy of this georeference', max_length=10),
        ),
    ]
