# Generated by Django 5.2.6 on 2025-09-27 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_alter_image_search_vector_precollection_preimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='ID of another Image if this is a duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='images.image'),
        ),
    ]
