# Generated by Django 5.2.6 on 2025-11-10 03:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0014_create_public_georeferences_mvt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="scale",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Scale: 1 (close-up/indoor), 2 (single building), 3 (multiple buildings), 4 (city block), 5 (wide landscape).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="Comment text content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commented_by",
                    models.ForeignKey(
                        help_text="User who made the comment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="image_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="images.image",
                    ),
                ),
            ],
            options={
                "ordering": ["image", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["image"], name="images_comm_image_i_7d3bad_idx"
                    ),
                    models.Index(
                        fields=["commented_by"], name="images_comm_comment_2d5433_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="images_comm_created_8e4733_idx"
                    ),
                ],
            },
        ),
    ]
