# Generated by Django 5.2.6 on 2025-11-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_album_albumimage_album_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aerial',
            field=models.BooleanField(default=False),
        ),
    ]
