# Generated by Django 5.2.6 on 2025-11-25 15:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0017_image_aerial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AerialGeoreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        help_text="Confidence level in the accuracy of this georeference",
                        max_length=10,
                    ),
                ),
                ("georeferenced_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confidence_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the georeferencing confidence or methodology",
                    ),
                ),
                (
                    "georeferenced_by",
                    models.ForeignKey(
                        help_text="User who submitted the georeference (null for anonymous submissions)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aerial_georeferenced_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aerial_georeferences",
                        to="images.image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AerialGeoreferenceValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validation",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("incorrect", "Incorrect"),
                            ("uncertain", "Uncertain"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Optional validation notes"),
                ),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "georeference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="images.aerialgeoreference",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aerial_georeference_validations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="aerialgeoreference",
            index=models.Index(
                fields=["image", "georeferenced_by"],
                name="images_aeri_image_i_61dab2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aerialgeoreference",
            index=models.Index(
                fields=["georeferenced_by"], name="images_aeri_georefe_df312a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aerialgeoreference",
            index=models.Index(
                fields=["georeferenced_at"], name="images_aeri_georefe_96816d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aerialgeoreferencevalidation",
            index=models.Index(
                fields=["georeference", "validation"],
                name="images_aeri_georefe_3ca313_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aerialgeoreferencevalidation",
            index=models.Index(
                fields=["validated_by"], name="images_aeri_validat_a08630_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aerialgeoreferencevalidation",
            unique_together={("georeference", "validated_by")},
        ),
    ]
