# Generated by Django 5.2.6 on 2025-12-03 04:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_create_top_rated_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsmElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(help_text='OpenStreetMap element ID', unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(help_text='Geometry of the OSM element (point, polygon, multipolygon, etc.)', srid=4326)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this row was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['osm_id'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='osm_element',
            field=models.ForeignKey(blank=True, help_text='Optional linked OpenStreetMap element', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='images.osmelement'),
        ),
    ]
