# Generated by Django 5.2.6 on 2025-12-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_osmelement_subject_osm_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmelement',
            name='geometry_area',
            field=models.FloatField(default=0, help_text='Cached area of the geometry in square degrees (used for render ordering)'),
        ),
    ]
