# Generated by Django 6.0 on 2026-01-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0031_image_detected_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="default_map_latitude",
            field=models.FloatField(
                default=33.98007413690877, help_text="Default map center latitude"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_map_longitude",
            field=models.FloatField(
                default=-117.37785664757142, help_text="Default map center longitude"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_map_zoom",
            field=models.IntegerField(
                default=10, help_text="Default map zoom level (0-22)"
            ),
        ),
    ]
