# Generated by Django 6.0 on 2026-01-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0032_sitesettings_default_map_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_map_zoom',
            field=models.FloatField(default=10.0, help_text='Default map zoom level (0-22, supports decimals like 11.5)'),
        ),
    ]
