# Generated by Django 6.0 on 2026-01-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0033_alter_sitesettings_default_map_zoom"),
    ]

    operations = [
        migrations.CreateModel(
            name="TileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "tile version",
                "verbose_name_plural": "tile version",
            },
        ),
    ]
