# Generated by Django 6.0 on 2026-01-31

from django.db import connection, migrations


def create_search_indexes(apps, schema_editor):
    """Create indexes to improve search performance."""
    if connection.vendor != "postgresql":
        return

    # Ensure required extensions are available
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # Create GiST trigram indexes on title and description for word similarity search
    # These support the <<-> operator used in text_search
    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS images_image_title_trgm_gist_idx
        ON images_image USING gist (title gist_trgm_ops);
    """)

    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS images_image_description_trgm_gist_idx
        ON images_image USING gist (description gist_trgm_ops);
    """)

    # Create GiST trigram indexes on related tables for text search
    # These support the <<-> operator used in text_search for comments and notes
    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS images_comment_text_trgm_gist_idx
        ON images_comment USING gist (text gist_trgm_ops);
    """)

    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS images_georeference_notes_trgm_gist_idx
        ON images_georeference USING gist (confidence_notes gist_trgm_ops)
        WHERE confidence_notes != '';
    """)

    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS images_aerialgeoreference_notes_trgm_gist_idx
        ON images_aerialgeoreference USING gist (confidence_notes gist_trgm_ops)
        WHERE confidence_notes != '';
    """)

    # Create HNSW index on embedding for vector similarity search
    # Using cosine distance operator class (vector_cosine_ops) to match <=> operator
    # Note: GiST doesn't support cosine ops, only HNSW and IVFFlat do
    # HNSW provides fast approximate nearest neighbor search with high recall
    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS images_image_embedding_hnsw_idx
        ON images_image USING hnsw ((embedding::vector(768)) vector_cosine_ops)
        WITH (m = 16, ef_construction = 64);
    """)


def drop_search_indexes(apps, schema_editor):
    """Remove search indexes."""
    if connection.vendor != "postgresql":
        return

    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS images_image_title_trgm_gist_idx;"
    )
    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS images_image_description_trgm_gist_idx;"
    )
    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS images_comment_text_trgm_gist_idx;"
    )
    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS images_georeference_notes_trgm_gist_idx;"
    )
    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS images_aerialgeoreference_notes_trgm_gist_idx;"
    )
    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS images_image_embedding_hnsw_idx;"
    )


class Migration(migrations.Migration):
    # atomic = False is required for CREATE INDEX CONCURRENTLY
    atomic = False

    dependencies = [
        ("images", "0034_tileversion"),
    ]

    operations = [
        migrations.RunPython(create_search_indexes, drop_search_indexes),
    ]
