# Generated by Django 6.0 on 2026-01-31

from django.db import connection, migrations, models


def populate_is_searchable(apps, schema_editor):
    """Populate is_searchable for all existing images based on collection/source visibility."""
    if connection.vendor != "postgresql":
        return

    # Use raw SQL for efficiency on large tables
    schema_editor.execute("""
        UPDATE images_image i
        SET is_searchable = (
            EXISTS (
                SELECT 1
                FROM images_collection c
                JOIN images_source s ON c.source_id = s.id
                WHERE c.id = i.collection_id
                AND c.public = true
                AND s.public = true
            )
            AND i.duplicate_of_id IS NULL
        )
    """)


def create_partial_indexes(apps, schema_editor):
    """Create partial indexes that only include searchable images."""
    if connection.vendor != "postgresql":
        return

    # Partial HNSW index on embedding for searchable images only
    # This dramatically reduces index size and improves vector search performance
    # Note: GiST doesn't support cosine ops, only HNSW and IVFFlat do
    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS images_image_searchable_embedding_hnsw_idx
        ON images_image USING hnsw ((embedding::vector(768)) vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        WHERE is_searchable = true AND embedding IS NOT NULL;
    """)

    # Partial GiST trigram indexes on title/description for searchable images only
    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS images_image_searchable_title_trgm_idx
        ON images_image USING gist (title gist_trgm_ops)
        WHERE is_searchable = true;
    """)

    schema_editor.execute("""
        CREATE INDEX CONCURRENTLY IF NOT EXISTS images_image_searchable_description_trgm_idx
        ON images_image USING gist (description gist_trgm_ops)
        WHERE is_searchable = true;
    """)


def drop_partial_indexes(apps, schema_editor):
    """Remove partial indexes."""
    if connection.vendor != "postgresql":
        return

    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS images_image_searchable_embedding_hnsw_idx;"
    )
    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS images_image_searchable_title_trgm_idx;"
    )
    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS images_image_searchable_description_trgm_idx;"
    )


class Migration(migrations.Migration):
    # atomic = False is required for CREATE INDEX CONCURRENTLY
    atomic = False

    dependencies = [
        ("images", "0035_enhance_search_vector"),
    ]

    operations = [
        # Add the is_searchable field
        migrations.AddField(
            model_name="image",
            name="is_searchable",
            field=models.BooleanField(
                default=False,
                db_index=True,
                help_text="Whether this image appears in search results (auto-computed from collection/source visibility and duplicate status)",
            ),
        ),
        # Populate the field for existing images
        migrations.RunPython(populate_is_searchable, migrations.RunPython.noop),
        # Create partial indexes for searchable images
        migrations.RunPython(create_partial_indexes, drop_partial_indexes),
    ]
