# Generated by Django 6.0 on 2026-01-31 06:06

from django.db import migrations


def populate_cached_html(apps, schema_editor):
    """Populate cached HTML fields for existing records."""
    from images.utils import render_markdown_safe

    Comment = apps.get_model("images", "Comment")
    Georeference = apps.get_model("images", "Georeference")
    AerialGeoreference = apps.get_model("images", "AerialGeoreference")

    # Update comments
    for comment in Comment.objects.filter(text_html=""):
        if comment.text:
            comment.text_html = render_markdown_safe(comment.text)
            comment.save(update_fields=["text_html"])

    # Update georeferences
    for geo in Georeference.objects.filter(confidence_notes_html=""):
        if geo.confidence_notes:
            geo.confidence_notes_html = render_markdown_safe(geo.confidence_notes)
            geo.save(update_fields=["confidence_notes_html"])

    # Update aerial georeferences
    for aerial in AerialGeoreference.objects.filter(confidence_notes_html=""):
        if aerial.confidence_notes:
            aerial.confidence_notes_html = render_markdown_safe(aerial.confidence_notes)
            aerial.save(update_fields=["confidence_notes_html"])


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0037_cache_rendered_markdown"),
    ]

    operations = [
        migrations.RunPython(populate_cached_html, migrations.RunPython.noop),
    ]
