# Generated by Django 6.0 on 2026-02-17 19:36

import django.db.models.deletion
from django.db import migrations, models

FLICKR_LICENSES = [
    {
        "id": 0,
        "name": "All Rights Reserved",
        "url": "https://www.flickrhelp.com/hc/en-us/articles/10710266545556-Using-Flickr-images-shared-by-other-members",
    },
    {
        "id": 1,
        "name": "CC BY-NC-SA 2.0",
        "url": "https://creativecommons.org/licenses/by-nc-sa/2.0/",
    },
    {
        "id": 2,
        "name": "CC BY-NC 2.0",
        "url": "https://creativecommons.org/licenses/by-nc/2.0/",
    },
    {
        "id": 3,
        "name": "CC BY-NC-ND 2.0",
        "url": "https://creativecommons.org/licenses/by-nc-nd/2.0/",
    },
    {
        "id": 4,
        "name": "CC BY 2.0",
        "url": "https://creativecommons.org/licenses/by/2.0/",
    },
    {
        "id": 5,
        "name": "CC BY-SA 2.0",
        "url": "https://creativecommons.org/licenses/by-sa/2.0/",
    },
    {
        "id": 6,
        "name": "CC BY-ND 2.0",
        "url": "https://creativecommons.org/licenses/by-nd/2.0/",
    },
    {
        "id": 7,
        "name": "No known copyright restrictions",
        "url": "https://www.flickr.com/commons/usage/",
    },
    {
        "id": 8,
        "name": "United States Government Work",
        "url": "https://www.usa.gov/government-copyright",
    },
    {
        "id": 9,
        "name": "Public Domain Dedication (CC0)",
        "url": "https://creativecommons.org/publicdomain/zero/1.0/",
    },
    {
        "id": 10,
        "name": "Public Domain Mark",
        "url": "https://creativecommons.org/publicdomain/mark/1.0/",
    },
    {
        "id": 11,
        "name": "CC BY 4.0",
        "url": "https://creativecommons.org/licenses/by/4.0/",
    },
    {
        "id": 12,
        "name": "CC BY-SA 4.0",
        "url": "https://creativecommons.org/licenses/by-sa/4.0/",
    },
    {
        "id": 13,
        "name": "CC BY-ND 4.0",
        "url": "https://creativecommons.org/licenses/by-nd/4.0/",
    },
    {
        "id": 14,
        "name": "CC BY-NC 4.0",
        "url": "https://creativecommons.org/licenses/by-nc/4.0/",
    },
    {
        "id": 15,
        "name": "CC BY-NC-SA 4.0",
        "url": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
    },
    {
        "id": 16,
        "name": "CC BY-NC-ND 4.0",
        "url": "https://creativecommons.org/licenses/by-nc-nd/4.0/",
    },
]


def seed_flickr_licenses(apps, schema_editor):
    License = apps.get_model("images", "License")
    for lic in FLICKR_LICENSES:
        License.objects.get_or_create(
            flickr_id=lic["id"],
            defaults={
                "name": lic["name"],
                "display_name": lic["name"],
                "permalink": lic["url"],
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0038_populate_cached_html"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "display_name",
                    models.CharField(
                        help_text="Name shown on the site", max_length=500
                    ),
                ),
                (
                    "permalink",
                    models.URLField(
                        blank=True, help_text="Link to license information", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Internal notes about this license"
                    ),
                ),
                (
                    "flickr_id",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Flickr license ID",
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_flickr_licenses, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="image",
            name="license_permalink",
        ),
        migrations.RemoveField(
            model_name="image",
            name="license_title",
        ),
        migrations.RemoveField(
            model_name="preimage",
            name="license_permalink",
        ),
        migrations.RemoveField(
            model_name="preimage",
            name="license_title",
        ),
        migrations.AddField(
            model_name="image",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="images.license",
            ),
        ),
        migrations.AddField(
            model_name="preimage",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pre_images",
                to="images.license",
            ),
        ),
    ]
