# Generated by Django 6.0.6 on 2026-07-02 07:42

import django.db.models.deletion
from django.db import migrations, models

# Frozen copy of CollectionStats.REFRESH_SQL (full-table variant) as of this
# migration, so the backfill always matches the schema created here
BACKFILL_SQL = """
INSERT INTO images_collectionstats (
    collection_id, total_images, will_not_georef_images,
    georeferenced_low, georeferenced_medium, georeferenced_high, updated_at
)
SELECT
    c.id,
    COUNT(img.id),
    COUNT(img.id) FILTER (WHERE img.will_not_georef),
    COUNT(img.id) FILTER (WHERE NOT img.will_not_georef AND conf.confidence = 'low'),
    COUNT(img.id) FILTER (WHERE NOT img.will_not_georef AND conf.confidence = 'medium'),
    COUNT(img.id) FILTER (WHERE NOT img.will_not_georef AND conf.confidence = 'high'),
    NOW()
FROM images_collection c
LEFT JOIN images_image img
    ON img.collection_id = c.id AND img.duplicate_of_id IS NULL
LEFT JOIN LATERAL (
    SELECT CASE WHEN img.aerial THEN (
        SELECT ag.confidence FROM images_aerialgeoreference ag
        WHERE ag.image_id = img.id
        ORDER BY ag.georeferenced_at DESC LIMIT 1
    ) ELSE (
        SELECT g.confidence FROM images_georeference g
        WHERE g.image_id = img.id
        ORDER BY g.georeferenced_at DESC LIMIT 1
    ) END AS confidence
) conf ON TRUE
GROUP BY c.id
ON CONFLICT (collection_id) DO UPDATE SET
    total_images = EXCLUDED.total_images,
    will_not_georef_images = EXCLUDED.will_not_georef_images,
    georeferenced_low = EXCLUDED.georeferenced_low,
    georeferenced_medium = EXCLUDED.georeferenced_medium,
    georeferenced_high = EXCLUDED.georeferenced_high,
    updated_at = EXCLUDED.updated_at
"""


def backfill_collection_stats(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(BACKFILL_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0057_sitesettings_home_feed_show_new_collections"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionStats",
            fields=[
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stats",
                        serialize=False,
                        to="images.collection",
                    ),
                ),
                ("total_images", models.PositiveIntegerField(default=0)),
                ("will_not_georef_images", models.PositiveIntegerField(default=0)),
                ("georeferenced_low", models.PositiveIntegerField(default=0)),
                ("georeferenced_medium", models.PositiveIntegerField(default=0)),
                ("georeferenced_high", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "collection stats",
            },
        ),
        migrations.RunPython(backfill_collection_stats, migrations.RunPython.noop),
    ]
