# Generated by Django 6.0.7 on 2026-08-13 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0063_duplicateimagepair_uuid'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='region',
            field=models.ForeignKey(blank=True, help_text="Region this collection's images depict, unless overridden on an image", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='regions.region'),
        ),
        migrations.AddField(
            model_name='image',
            name='region',
            field=models.ForeignKey(blank=True, help_text="Region this image depicts; falls back to the collection's, then the source's", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='regions.region'),
        ),
        migrations.AddField(
            model_name='source',
            name='region',
            field=models.ForeignKey(blank=True, help_text="Region this source's images depict, unless overridden on a collection or image", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='regions.region'),
        ),
    ]
