# Generated by Django 6.0.7 on 2026-08-13 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0019_wikidataitem_demolished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the region', max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wikidata_item', models.OneToOneField(help_text='Linked Wikidata item', on_delete=django.db.models.deletion.CASCADE, related_name='region', to='subjects.wikidataitem')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RegionAncestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='subjects.wikidataitem')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='regions.region')),
            ],
            options={
                'indexes': [models.Index(fields=['ancestor'], name='regions_reg_ancesto_d70e0a_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'ancestor'), name='regionancestor_unique_pair')],
            },
        ),
    ]
