# Generated by Django 6.0 on 2026-01-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="osmelement",
            name="metadata_fetch_failures",
            field=models.PositiveIntegerField(
                default=0, help_text="Consecutive fetch failures (resets on success)"
            ),
        ),
        migrations.AddField(
            model_name="osmelement",
            name="metadata_last_fetched",
            field=models.DateTimeField(
                blank=True,
                help_text="When we last attempted to fetch geometry from OSM",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wikidataitem",
            name="metadata_fetch_failures",
            field=models.PositiveIntegerField(
                default=0, help_text="Consecutive fetch failures (resets on success)"
            ),
        ),
        migrations.AddField(
            model_name="wikidataitem",
            name="metadata_last_fetched",
            field=models.DateTimeField(
                blank=True,
                help_text="When we last attempted to fetch metadata from Wikidata",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="wikidataitem",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this row was last modified"
            ),
        ),
    ]
