# Generated by Django 6.0 on 2026-01-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0002_osmelement_metadata_fetch_failures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="osm_last_checked",
            field=models.DateTimeField(
                blank=True,
                help_text="When we last attempted to find an OSM element for this subject",
                null=True,
            ),
        ),
    ]
