# Generated by Django 6.0 on 2026-01-28 04:11
# populate_centroids and reverse_populate_centroids added after

import django.contrib.gis.db.models.fields
from django.db import migrations


def populate_centroids(apps, schema_editor):
    OsmElement = apps.get_model("subjects", "OsmElement")
    for element in OsmElement.objects.filter(geometry__isnull=False):
        element.centroid = element.geometry.centroid
        element.save(update_fields=["centroid"])


def reverse_populate_centroids(apps, schema_editor):
    OsmElement = apps.get_model("subjects", "OsmElement")
    OsmElement.objects.update(centroid=None)


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0003_subject_osm_last_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="osmelement",
            name="centroid",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Centroid of the geometry (auto-populated on save)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.RunPython(populate_centroids, reverse_populate_centroids),
    ]
