# Generated by Django 6.0 on 2026-01-28 06:29

import django.db.models.deletion
from django.db import migrations, models


def migrate_osm_element_relationships(apps, schema_editor):
    """
    Migrate existing Subject.osm_element relationships to OsmElement.subject.
    """
    Subject = apps.get_model("subjects", "Subject")

    for subject in Subject.objects.filter(osm_element__isnull=False):
        osm_element = subject.osm_element
        osm_element.subject = subject
        osm_element.save(update_fields=["subject"])


def reverse_migrate_osm_element_relationships(apps, schema_editor):
    """
    Reverse migration: copy OsmElement.subject back to Subject.osm_element.
    Note: Only preserves one OsmElement per Subject (the first one found).
    """
    OsmElement = apps.get_model("subjects", "OsmElement")

    for osm_element in OsmElement.objects.filter(subject__isnull=False):
        subject = osm_element.subject
        subject.osm_element = osm_element
        subject.save(update_fields=["osm_element"])


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0004_osmelement_centroid"),
    ]

    operations = [
        # Step 1: Add the new subject field to OsmElement
        migrations.AddField(
            model_name="osmelement",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject this OSM element belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="osm_elements",
                to="subjects.subject",
            ),
        ),
        # Step 2: Migrate data from Subject.osm_element to OsmElement.subject
        migrations.RunPython(
            migrate_osm_element_relationships,
            reverse_migrate_osm_element_relationships,
        ),
        # Step 3: Remove the old osm_element field from Subject
        migrations.RemoveField(
            model_name="subject",
            name="osm_element",
        ),
    ]
