# Generated by Django 6.0 on 2026-01-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_move_osm_element_fk_to_osmelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osmelement',
            name='metadata_fetch_failures',
        ),
        migrations.RemoveField(
            model_name='osmelement',
            name='metadata_last_fetched',
        ),
    ]
